from __future__ import annotations
import argparse, hashlib, json, stat, zipfile
from pathlib import Path, PurePosixPath

ROOT=Path(__file__).resolve().parents[1]
PKG='r5_n4_hw_v75_sourcebound_collectfix'; SOURCE='r5_n4_hw_v74_sourcebound_epoch_diag'
def h(b): return hashlib.sha256(b).hexdigest()
def hf(p): return h(Path(p).read_bytes())
def main():
 p=argparse.ArgumentParser(); p.add_argument('--zip',type=Path,required=True); p.add_argument('--repeat',type=Path,required=True); p.add_argument('--output',type=Path,required=True); a=p.parse_args(); checks={}
 with zipfile.ZipFile(a.zip) as z:
  infos=z.infolist(); names=[i.filename for i in infos]; checks['crc']=z.testzip() is None; checks['single_root']={n.split('/',1)[0] for n in names}=={PKG}; checks['safe']=all(not PurePosixPath(n).is_absolute() and '..' not in PurePosixPath(n).parts and '\\' not in n and not stat.S_ISLNK(i.external_attr>>16) for n,i in zip(names,infos)); checks['duplicates']=len(names)==len(set(names)); files={n.split('/',1)[1]:z.read(n) for n in names if '/' in n}; m=json.loads(files['package_manifest.json']); actual={k:h(v) for k,v in files.items() if k!='package_manifest.json'}; checks['manifest']=m['files']==actual; r=m['active_receipts']; checks['current_receipts']=r.get('source_bound_generator_sha256')==hf(ROOT/'tools/generate_server_source_bound_observer.py') and r.get('server_package_rule_sha256')==hf(ROOT/'.agents/rules/服务器测试包生成规则.md') and r.get('server_post_sim_return_helper_sha256')==hf(ROOT/'tools/server_post_sim_return.py'); checks['frozen']=all(m.get(k) is False for k in ('numeric_analysis_repeated','node0004_workload_rebuilt','configuration_rebuilt','functional_rtl_modified','server_action')); checks['post_sim_members']=all(k in files for k in ('package_tools/server_post_sim_return.py','contracts/server_post_sim_return_request.json','contracts/server_post_sim_return_contract.json'))
 checks['deterministic']=hf(a.zip)==hf(a.repeat); checks['source_bound_gate']=json.loads((ROOT/'outputs/conv_node0004_v74_recovered_return_v75_successor/source_bound_final_zip_validation_final_c.json').read_text())['pass']; checks['post_sim_gate']=json.loads((ROOT/'outputs/conv_node0004_v74_recovered_return_v75_successor/post_sim_final_zip_validation_final_c.json').read_text())['pass']; checks['v74_replay']=json.loads((ROOT/'outputs/conv_node0004_v74_recovered_return_v75_successor/v74_replay_decision.json').read_text())['decision']=='POST_TERMINAL_TEMPORAL_OWNERSHIP_REQUIRES_RING'
 errors=[k for k,v in checks.items() if not v]; out={'schema':'conv-node0004-v75-final-zip-audit-v1','FINAL_ZIP_RULE_SELF_AUDIT_PASS':not errors,'errors':errors,'checks':checks,'zip':{'path':str(a.zip.resolve()),'bytes':a.zip.stat().st_size,'sha256':hf(a.zip)},'release_gate_matrix':{'package_bootstrap':{'blocking':True,'pass':checks['manifest']},'source_bound_observer':{'blocking':True,'pass':checks['source_bound_gate']},'post_sim_core_return':{'blocking':True,'pass':checks['post_sim_gate']},'numeric_workload_config':{'blocking':False,'applicability':'receipt_reuse_frozen','pass':checks['frozen']}},'claim_boundary':'Local package gates only; no server run, natural terminal, formal D, E4 or E5 claim.'}; a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n',encoding='utf-8'); print(json.dumps({'pass':not errors,'errors':errors})); return 0 if not errors else 1
if __name__=='__main__': raise SystemExit(main())
