from __future__ import annotations

import argparse, hashlib, json, stat, zipfile
from pathlib import Path, PurePosixPath

ROOT=Path(__file__).resolve().parents[1]
PACKAGE="r5_n4_hw_v67_pe1_pair_diag"
SOURCE_SHA="b0f4a0d83a82ccd1b039247da09318a1d9121ae08a9857f268a8568538050d1e"
RULES={"agent":ROOT/".agents/agent.md","plan_mutable":ROOT/".agents/plan.md","index":ROOT/".agents/rules/生成前必读索引.md","server":ROOT/".agents/rules/服务器测试包生成规则.md","common":ROOT/".agents/rules/算子配置规则.md","ndp":ROOT/".agents/rules/NDP硬件字段语义.md","int8_sa":ROOT/".agents/rules/INT8_SA点积专项规则.md","readme":ROOT/"NDP_copy01/README_HARDWARE_SIM_ENTRY.md"}
def sha(b:bytes)->str:return hashlib.sha256(b).hexdigest()
def shaf(p:Path)->str:return sha(p.read_bytes())
def load(p:Path):return json.loads(p.read_text(encoding='utf-8'))

def main()->int:
    ap=argparse.ArgumentParser(); ap.add_argument('--zip',required=True,type=Path); ap.add_argument('--sidecar',required=True,type=Path); ap.add_argument('--source-v66',required=True,type=Path); ap.add_argument('--build-report',required=True,type=Path); ap.add_argument('--family-report',required=True,type=Path); ap.add_argument('--shared-report',required=True,type=Path); ap.add_argument('--observer-report',required=True,type=Path); ap.add_argument('--runner-report',required=True,type=Path); ap.add_argument('--return-report',required=True,type=Path); ap.add_argument('--output',required=True,type=Path); a=ap.parse_args()
    checks={}; zsha=shaf(a.zip); checks['source_identity']=shaf(a.source_v66)==SOURCE_SHA; checks['sidecar_identity']=a.sidecar.read_text(encoding='ascii').split()==[zsha,a.zip.name]
    with zipfile.ZipFile(a.zip) as z, zipfile.ZipFile(a.source_v66) as s:
        infos=z.infolist(); names=[i.filename for i in infos]; checks['crc']=z.testzip() is None; checks['single_root']={x.split('/',1)[0] for x in names}=={PACKAGE}; checks['no_duplicates']=len(names)==len(set(names)); checks['safe_paths']=all(not PurePosixPath(i.filename).is_absolute() and '..' not in PurePosixPath(i.filename).parts and '\\' not in i.filename for i in infos); checks['no_symlinks']=all(not stat.S_ISLNK((i.external_attr>>16)&0xffff) for i in infos)
        target={'/'.join(i.filename.split('/')[1:]):z.read(i) for i in infos if not i.is_dir()}; sr=s.namelist()[0].split('/',1)[0]; source={'/'.join(i.filename.split('/')[1:]):s.read(i) for i in s.infolist() if not i.is_dir()}; m=json.loads(target['package_manifest.json']); actual={p:sha(b) for p,b in target.items() if p!='package_manifest.json'}
        checks['manifest_exact_set']=set(m['files'])==set(actual); checks['manifest_receipts']=m['files']==actual; checks['manifest_identity']=m['install_name']==PACKAGE and m['source_package_sha256']==SOURCE_SHA and m['classification']=='DIAGNOSTIC_ONLY_NOT_FUNCTIONAL_FIX' and m['candidate_release'] is False and m['configuration_rebuilt'] is False and m['node0004_workload_rebuilt'] is False and m['numeric_analysis_repeated'] is False and m['functional_rtl_modified'] is False and m['server_action'] is False
        c=m['diagnostic_features']['RETURN_OBS_PE1_PAIR']; checks['feature_contract']=c['runtime_enable_parameter']=='+RETURN_OBS_PE1_PAIR' and c['limit_parameter']=='+RETURN_OBS_PE1_PAIR_LIMIT=128' and c['edge_schema']=='PE1_PAIR_V1'
        runner=target['PREPARE_AND_RUN.sh'].decode(); checks['feature_actual_argv']=runner.count(' +RETURN_OBS_PE1_PAIR +RETURN_OBS_PE1_PAIR_LIMIT=128')==2; checks['install_only_v2']=json.loads(target['SERVER_RUNTIME_LAYOUT_CONTRACT.json'])['required_preexisting_parents']==['install']; checks['fresh_provenance']='provenance/v66_to_v67_pe1_pair.json' in target
        frozen=[p for p in source if (p.startswith('workload/') or 'golden' in p.lower() or p.endswith('.bin')) and p in target]; checks['frozen_payload']=bool(frozen) and all(target[p].replace(PACKAGE.encode(),sr.encode())==source[p] for p in frozen)
        receipts=m.get('active_receipts',{}); checks['current_rule_receipts']=receipts.get('generation_index_sha256')==shaf(RULES['index']) and receipts.get('server_package_rule_sha256')==shaf(RULES['server']) and receipts.get('int8_sa_rule_sha256')==shaf(RULES['int8_sa'])
    reports={'build':load(a.build_report).get('deterministic_rebuild_equal') is True,'family':load(a.family_report).get('valid') is True,'shared':load(a.shared_report).get('pass') is True,'observer':load(a.observer_report).get('valid') is True,'runner':load(a.runner_report).get('valid') is True,'return':load(a.return_report).get('valid') is True}; checks.update({f'{k}_report':v for k,v in reports.items()})
    matrix={"package_bootstrap_path_runtime_d":{"applicability":"receipt_reuse","blocking":True,"pass":checks['family_report'] and checks['shared_report']},"runner_compile_finalizer":{"applicability":"receipt_reuse","blocking":True,"pass":checks['family_report'] and checks['runner_report']},"package_local_hdl_changed":{"applicability":"blocking_applicable","blocking":True,"pass":checks['observer_report']},"materialized_config":{"applicability":"not_applicable_byte_equal","blocking":False,"pass":True},"observer_canonical_changed":{"applicability":"blocking_applicable","blocking":True,"pass":checks['observer_report']},"return_result_gate":{"applicability":"receipt_reuse","blocking":True,"pass":checks['return_report']},"numeric_w3_golden":{"applicability":"record_only_byte_equal","blocking":False,"pass":checks['frozen_payload']},"unrelated_rtl":{"applicability":"not_applicable","blocking":False,"pass":True}}
    checks['release_gate_matrix']=all((not r['blocking']) or r['pass'] for r in matrix.values()); errors=[k for k,v in checks.items() if not v]
    report={"schema":"node0004-v67-final-zip-audit-v1","FINAL_ZIP_RULE_SELF_AUDIT_PASS":not errors,"errors":errors,"checks":checks,"zip":{"path":str(a.zip.resolve()),"bytes":a.zip.stat().st_size,"sha256":zsha},"current_rule_receipts":{k:{"path":str(p),"sha256":shaf(p)} for k,p in RULES.items()},"release_gate_matrix":matrix,"claim_boundary":"Exact final ZIP, changed PE1 pair observer and v66 shadow-width correction, runner/layout/finalizer and result gate only; no DUT natural terminal/formal320D/E4/E5 claim."}
    a.output.parent.mkdir(parents=True,exist_ok=True); a.output.write_text(json.dumps(report,indent=2,sort_keys=True)+'\n',encoding='utf-8',newline='\n'); print(json.dumps({"pass":not errors,"errors":errors,"sha":zsha})); return 0 if not errors else 1
if __name__=='__main__':raise SystemExit(main())
