#!/usr/bin/env python3
from __future__ import annotations
import argparse, hashlib, json, stat, zipfile
from pathlib import Path, PurePosixPath
PACKAGE="r5_n4_hw_v83b_phase_stable_diag"; RULE_SHA="74ae37513d6bcb763543a7a4583ec1acea3d4b2919f07ab8fab266272bf3cc0b"; INDEX_SHA="991740fe543243c1697174fe9c9621af0201469c8bab37c95ea4db12d8276f2c"; GENERATOR_SHA="c50c2f8117ee6e73da76cae4c5a0fc46a3774b7c775d9bb62942ff8bcd4b837f"; PRIOR_PASS="0c71f0972193e7a2e6a1b9f0609d45198129c5c1da629cf9ba977445d310f71a"
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p:Path)->dict:return json.loads(p.read_text(encoding="utf-8"))
def receipt(p:Path)->dict:return {"path":str(p),"bytes":p.stat().st_size,"sha256":sha(p)}
def main()->int:
 ap=argparse.ArgumentParser();ap.add_argument("--zip",type=Path,required=True);ap.add_argument("--sidecar",type=Path,required=True);ap.add_argument("--build-report",type=Path,required=True);ap.add_argument("--validation-root",type=Path,required=True);ap.add_argument("--output",type=Path,required=True);a=ap.parse_args()
 paths={"source_bound":a.validation_root/"validation_v83b_source_bound.json","phase":a.validation_root/"validation_v83b_phase.json","post_sim":a.validation_root/"validation_v83b_post_sim.json","runner":a.validation_root/"validation_v83b_runner.json","shared_harness":a.validation_root/"validation_v83b_shared_harness.json","runtime_layout":a.validation_root/"validation_v83b_runtime_layout.json","return_contract":a.validation_root/"validation_v83b_return_contract.json"};values={k:load(v) for k,v in paths.items() if v.is_file()};missing=sorted(set(paths)-set(values));build=load(a.build_report)
 with zipfile.ZipFile(a.zip) as z:
  infos=z.infolist();names=[x.filename for x in infos];prefix=PACKAGE+"/";crc=z.testzip() is None;safe=all(not PurePosixPath(x.filename).is_absolute() and ".." not in PurePosixPath(x.filename).parts and "\\" not in x.filename and not stat.S_ISLNK(x.external_attr>>16) for x in infos);root={PurePosixPath(n).parts[0] for n in names if n}=={PACKAGE};dups=len(names)==len(set(names));manifest=json.loads(z.read(prefix+"package_manifest.json"));actual={x.filename[len(prefix):]:hashlib.sha256(z.read(x)).hexdigest() for x in infos if x.filename.startswith(prefix) and x.filename!=prefix+"package_manifest.json" and not x.is_dir()};sem=json.loads(z.read(prefix+"diagnostics/buffer_ack_phase_semantics_contract.json"));request=json.loads(z.read(prefix+"contracts/server_post_sim_return_request.json"));runner=z.read(prefix+"PREPARE_AND_RUN.sh").decode();phase_hashes={"observer":hashlib.sha256(z.read(prefix+"tb_probe/buffer_ack_phase_observer.svh")).hexdigest(),"parser":hashlib.sha256(z.read(prefix+"package_tools/buffer_ack_phase_parser.py")).hexdigest(),"plugin":hashlib.sha256(z.read(prefix+"package_tools/node0004_v83_post_sim_plugin.py")).hexdigest()}
 side=a.sidecar.read_text(encoding="ascii").split();active=manifest.get("active_receipts",{});ack=manifest.get("first_fresh_extra_audit",{})
 checks={"crc":crc,"safe":safe,"root":root,"duplicate_free":dups,"sidecar":len(side)>=2 and side[0]==sha(a.zip) and side[-1].endswith(a.zip.name),"manifest_exact":manifest.get("files")==actual,"build_identity":build.get("zip_sha256")==sha(a.zip) and build.get("zip_bytes")==a.zip.stat().st_size and build.get("deterministic_directory_rebuild_equal") is True,"one_aggregate_one_zip":build.get("cheap_aggregate_invocations")==1 and build.get("final_zip_count")==1,"current_rule":active.get("server_package_rule_sha256")==RULE_SHA,"current_index":active.get("generation_index_sha256")==INDEX_SHA,"current_generator":active.get("source_bound_generator_sha256")==GENERATOR_SHA,"prior_first_fresh_reuse":ack.get("first_fresh_after_change") is False and ack.get("prior_first_fresh_pass_receipt_sha256")==PRIOR_PASS and build.get("prior_first_fresh_pass_receipt_sha256")==PRIOR_PASS,"source_bound":values.get("source_bound",{}).get("pass") is True and values.get("source_bound",{}).get("semantic_controls",{}).get("pass") is True,"phase":values.get("phase",{}).get("pass") is True and values.get("phase",{}).get("errors")==[],"post_sim":values.get("post_sim",{}).get("pass") is True and values.get("post_sim",{}).get("errors")==[],"runner":values.get("runner",{}).get("valid") is True and values.get("runner",{}).get("errors")==[],"runtime_layout":values.get("runtime_layout",{}).get("pass") is True and values.get("runtime_layout",{}).get("errors")==[],"return_contract":values.get("return_contract",{}).get("valid") is True and values.get("return_contract",{}).get("errors")==[],"phase_hashes":sem.get("observer_sha256")==phase_hashes["observer"] and sem.get("parser_sha256")==phase_hashes["parser"] and sem.get("post_sim_plugin_sha256")==phase_hashes["plugin"],"edge_free_schedule":sem.get("phases")==["PRE","EDGE","DELTA_1PS","QUARTER_250PS","LATE_750PS"] and sem.get("collector_order")=="STABLE_PHASE_PARSE_AND_PERSIST_BEFORE_BOUNDED_SOURCE_BOUND_PROJECTION","request_plugin":"node0004_v83_post_sim_plugin.py" in json.dumps(request),"runner_handoff":all(x in runner for x in ("source_bound_causal_observer.svh","buffer_ack_phase_observer.svh","+CODEX_CAUSAL_OBSERVER","+RETURN_OBS_BUF_ACK_PHASE_LIMIT=128")),"all_reports":not missing}
 matrix={"package_bootstrap_path_runtime_D":{"applicability":"blocking_applicable","pass":all(checks[k] for k in ("crc","safe","root","duplicate_free","sidecar","manifest_exact"))},"actual_runner_compile_finalizer_and_86_inputs":{"applicability":"blocking_applicable","pass":checks["runner"] and checks["runtime_layout"]},"actual_package_local_HDL":{"applicability":"blocking_applicable","pass":checks["source_bound"] and checks["phase"] and checks["phase_hashes"]},"changed_observer_and_canonical_semantics":{"applicability":"blocking_applicable","pass":checks["source_bound"] and checks["phase"] and checks["edge_free_schedule"] and checks["post_sim"]},"return_result_joint_gate":{"applicability":"blocking_applicable","pass":checks["return_contract"]},"first_fresh_independent_reaudit":{"applicability":"receipt_reuse","pass":checks["prior_first_fresh_reuse"],"receipt_sha256":PRIOR_PASS},"materialized_config":{"applicability":"receipt_reuse","pass":True,"reason":"byte-identical frozen v82b config/address/workload"},"numeric_W3_golden":{"applicability":"not_applicable","pass":True},"functional_RTL":{"applicability":"not_applicable","pass":True}}
 errors=[k for k,v in checks.items() if not v]+["release_gate:"+k for k,v in matrix.items() if v.get("pass") is not True];out={"schema":"conv-node0004-v83-final-zip-audit-v1","FINAL_ZIP_RULE_SELF_AUDIT_PASS":not errors,"errors":errors,"checks":checks,"release_gate_matrix":matrix,"zip":receipt(a.zip),"active_receipts":{"server_rule_sha256":RULE_SHA,"generation_index_sha256":INDEX_SHA,"generator_sha256":GENERATOR_SHA},"report_receipts":{k:receipt(v) for k,v in paths.items()},"claims":{"numeric_analysis_repeated":False,"workload_rebuilt":False,"configuration_rebuilt":False,"functional_rtl_modified":False,"server_action":False},"claim_boundary":"Exact final package and diagnostic gates only; no natural-terminal, formal-D, E3/E4/E5 claim."};a.output.parent.mkdir(parents=True,exist_ok=True);a.output.write_text(json.dumps(out,indent=2,sort_keys=True)+"\n",encoding="utf-8");print(json.dumps({"pass":not errors,"errors":errors,"zip_sha256":sha(a.zip)}));return 0 if not errors else 1
if __name__=="__main__":raise SystemExit(main())
