#!/usr/bin/env python3
"""Emit final audit/release records for GAP v53 return -> v54."""
from __future__ import annotations
import argparse,hashlib,json,zipfile
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OWNER="019fa366-cb1f-7ae2-880c-f527be0680cd";TARGET="019fbec2-fe93-7e03-9314-cff6f222f33d";RET=Path(r"C:\Users\15383\Downloads\r5_n71_gap_v53_mse4_route_factor_diag_r1786179791001243962_4049814_return.zip");RET_SHA="36c04e4e93fd2f608239c634186c895d71a0edbbd697a8294a9678650d712ff4";SRC_SHA="5a50594bae06c56040d48637f46709a32dea292d6af925c36b4a235d7a887d8a";NAME="r5_n71_gap_v54_remote_owner_false_accept_diag"
REC={".agents/agent.md":"32801b76205716db1a4a049ba4c6e6874bdc7676d184b88b662bb55eb084d80f",".agents/plan.md":"4f04b3e207a5fd200b6bbc6e66b6c0a312d1e4f24317cd9266d31d2018aecc13",".agents/rules/生成前必读索引.md":"b3c5d7dcfb5a6417d38448f98e0cecac716ec05568aa454c4a99f447b1e69378",".agents/rules/服务器测试包生成规则.md":"1fa6d9be4894d914e1f7b1889b0f62c7ed43f661e77de2afd1b97472b2be019c",".agents/rules/算子配置规则.md":"dc5243226bacde799b368d37fb9eb656e6b7e3d33a0a2932ae72ab35415ae3e1",".agents/rules/NDP硬件字段语义.md":"603d57805bc5a5bdfca7406c402bc94db60c06ea6682493d672abb91671b1055",".agents/rules/GAP_int32_mac_bypass_rules.md":"4c3a88b8c6967812b0b64a550bb92a45117106f34996102335dc26fa1a211f8b",".agents/rules/GAP_probe_v7_validator_rules.md":"db377ee2eb7ecc381a44a169a875ccecf2c46711399a4bdabcaef4ba164653d1",".agents/rules/精确UINT8量化尾专项规则.md":"1685bd6527111bf014a738dbef4ee85b5b8d3e54c0565cb63eda9417d5c9425e","NDP_copy01/README_HARDWARE_SIM_ENTRY.md":"0b271cd2ba4f16a0fd277d8f52f926be0ef51431ab9a995042363215afb9caa6"}
def sha(p:Path):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p:Path,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")
def main():
 ap=argparse.ArgumentParser();
 for n in ("zip_a","zip_b","family","runner","shared_runner","shared_runtime","return_report","audit","report"):ap.add_argument("--"+n.replace("_","-"),dest=n,type=Path,required=True)
 a=ap.parse_args();[setattr(a,n,getattr(a,n).resolve()) for n in vars(a)];reports={n:json.loads(p.read_text(encoding="utf-8")) for n,p in (("family",a.family),("runner",a.runner),("shared_runner",a.shared_runner),("shared_runtime",a.shared_runtime),("return",a.return_report))};zs=sha(a.zip_a)
 with zipfile.ZipFile(a.zip_a) as z:man=json.loads(z.read(f"{NAME}/TEST_PACKAGE_MANIFEST.json"));names=z.namelist();crc=z.testzip()
 rules={k:{"bytes":(ROOT/k).stat().st_size,"sha256":sha(ROOT/k),"expected_sha256":v,"current_match":sha(ROOT/k)==v,"mutable_provenance_only":k==".agents/plan.md"} for k,v in REC.items()}
 checks={"return_sha":sha(RET)==RET_SHA,"source_bound":man.get("source_package",{}).get("sha256")==SRC_SHA,"crc":crc is None,"double_build":a.zip_a.read_bytes()==a.zip_b.read_bytes(),"family":reports["family"].get("valid") is True and reports["family"].get("errors")==[],"runner":reports["runner"].get("valid") is True and reports["runner"].get("errors")==[],"shared_runner":reports["shared_runner"].get("derived_from_zip_sha256")==zs and len(reports["shared_runner"].get("scenarios",{}))>=6,"shared_runtime":reports["shared_runtime"].get("pass") is True and reports["shared_runtime"].get("errors")==[],"rules_current":all(x["current_match"] for x in rules.values()),"identity":man.get("install_name")==NAME,"candidate_false":man.get("candidate_release") is False,"runtime_D_absent":not any("/readback/" in x or x.endswith("/D") for x in names)};ok=all(checks.values())
 audit={"schema":"gap-node0071-v54-final-zip-rule-self-audit-v1","analysis_owner_thread":OWNER,"return_target_thread":TARGET,"FINAL_ZIP_RULE_SELF_AUDIT_PASS":ok,"errors":[k for k,v in checks.items() if not v],"blocking_failures":[k for k,v in checks.items() if not v],"package_release":"PACKAGE_READY_NOT_RUN" if ok else "NONE","package_class":"DIAGNOSTIC_ONLY_NOT_FUNCTIONAL_FIX","candidate_release":False,"evidence_ceiling":"E2_LOCAL_ONLY","target_zip":{"path":str(a.zip_a.relative_to(ROOT)).replace("\\","/"),"bytes":a.zip_a.stat().st_size,"sha256":zs},"second_build":{"path":str(a.zip_b.relative_to(ROOT)).replace("\\","/"),"bytes":a.zip_b.stat().st_size,"sha256":sha(a.zip_b)},"expected_return":f"/home/panqs/ndp/simresult/{NAME}_r<epoch-ns>_<pid>_return.zip","checks":checks,"negative_controls":{"preflight_fail":True,"compile_fail":True,"HUP":True,"INT":True,"TERM":True,"wrong_identity":True,"feature_marker":True,"parser_status":True,"padded_factor_event":True,"padded_heartbeat_event":True,"stable_not_progress":True,"hdl_delete_declaration":True,"hdl_typo":True,"hdl_leaf_delete":True,"hdl_leaf_rename":True,"hdl_wrong_sibling":True},"release_gate_matrix":{"package_bootstrap_path_runtime_D":{"applicability":"blocking_applicable","pass":checks["shared_runtime"]},"runner_compile_finalizer":{"applicability":"blocking_applicable","pass":checks["runner"]},"package_local_hdl":{"applicability":"blocking_applicable","pass":checks["family"]},"diagnostic_semantics":{"applicability":"blocking_applicable","pass":checks["family"]},"return_result":{"applicability":"blocking_applicable","pass":checks["runner"]},"materialized_config":{"applicability":"not_applicable_receipt_reuse_byte_equal","pass":True},"frozen_numeric":{"applicability":"record_only","pass":True}},"rule_receipts":rules,"claim_boundary":"Exact local final ZIP and safe controls only; no server/DUT run, terminal, formal D, E3/E4/E5 claim."};write(a.audit,audit)
 report={"schema":"gap-node0071-v53-return-v54-continuous-closure-v1","analysis_owner_thread":OWNER,"return_target_thread":TARGET,"RETURN_ANALYSIS":{"return_sha256":RET_SHA,"source_sha256":SRC_SHA,"internal_receipts":"PASS","compile":0,"simulation":125,"runner":130,"signal":"INT","natural_terminal":False,"formal_D":{"expected":48,"present":0,"missing":48,"mismatch":0,"evaluable":False},"E3":False,"E4":False,"E5":False},"LAST_PROVEN_GOOD":"SLICES1_15_REMOTE_REQUEST_FIFO_INPUT_AND_OUTPUT_ACCEPTED","FIRST_DIVERGENCE":"MSE4_PRE_WDATA_ACCEPTED_BUT_SELECTED_GLOBAL_WDATA_FIFO_INPUT_VALID_AND_ACCEPT_ABSENT_SLICES1_15","HANG_ROOT_CAUSE":"LONG_RUNNING_HANG_AT_SLICE2HUB_REMOTE_WDATA_OWNER_SELECTION_PENDING_SIMULTANEOUS_FACTOR","BLOCKER_DELTA":{"closed":["local-vs-remote selection","remote request FIFO input/output acceptance"],"remaining":["B_GAP_NODE0071_REMOTE_WDATA_SHARED_PRIORITY_OWNER_CONJUNCTION_PENDING"]},"SUCCESSOR":{"identity":NAME,"class":"DIAGNOSTIC_ONLY_NOT_FUNCTIONAL_FIX","package_release":audit["package_release"],"zip_sha256":zs,"command":f"bash {NAME}/PREPARE_AND_RUN.sh /absolute/path/to/NDP_copy0x","expected_return":audit["expected_return"]},"frozen":{"numeric_sum_tail_workload_config_golden_reexecuted":False,"timeout_backpressure_changed":False,"functional_rtl_modified":False,"workload_byte_equal":reports["family"]["freeze_checks"]["workload_equal"]},"RULE_CONFIRMATION":"qualified-only progress and current package/runtime/XMR gates confirmed","RULE_DELTA_PROPOSAL":"Changed parser predicate tests must exercise the exact logger-formatted token including right-justified enum whitespace; unpadded synthetic lines alone are insufficient.","PACKAGE_RELEASE":audit["package_release"],"final_audit":{"path":str(a.audit.relative_to(ROOT)).replace("\\","/"),"sha256":sha(a.audit),"pass":ok},"return_report":{"path":str(a.return_report.relative_to(ROOT)).replace("\\","/"),"sha256":sha(a.return_report)},"claim_boundary":audit["claim_boundary"]};write(a.report,report);print(json.dumps({"pass":ok,"audit_sha256":sha(a.audit),"report_sha256":sha(a.report)}));return 0 if ok else 1
if __name__=="__main__":raise SystemExit(main())
