#!/usr/bin/env python3
"""Changed-surface validation for exact GAP v54 ZIP."""
from __future__ import annotations
import argparse,hashlib,json,re,stat,subprocess,sys,tempfile,zipfile
from pathlib import Path,PurePosixPath
ROOT=Path(__file__).resolve().parents[1];NAME="r5_n71_gap_v54_remote_owner_false_accept_diag";SOURCE_NAME="r5_n71_gap_v53_mse4_route_factor_diag";SOURCE=ROOT/"artifacts/operator_config_validation/r5-server-test-packages/pending"/f"{SOURCE_NAME}.zip";SOURCE_SHA="5a50594bae06c56040d48637f46709a32dea292d6af925c36b4a235d7a887d8a";INDEX_SHA="b3c5d7dcfb5a6417d38448f98e0cecac716ec05568aa454c4a99f447b1e69378";SERVER_SHA="1fa6d9be4894d914e1f7b1889b0f62c7ed43f661e77de2afd1b97472b2be019c";MARKER="    // v54: simultaneous shared-remote owner and false-accept proof.";IV=Path(r"C:\iverilog\bin\iverilog.exe");CROSS=ROOT/"NDP_copy01/rtl/Slice/slice2hub_crossbar.sv";FIFO=ROOT/"NDP_copy01/rtl/utils/FIFO/FIFO.sv";INC=ROOT/"NDP_copy01/rtl/includes"
def h(b:bytes):return hashlib.sha256(b).hexdigest()
def sha(p:Path):return h(p.read_bytes())
def write(p:Path,v):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(v,ensure_ascii=False,indent=2,sort_keys=True)+"\n",encoding="utf-8",newline="\n")
def zmap(p:Path,root:str):
 with zipfile.ZipFile(p) as z:
  i=z.infolist();n=[x.filename for x in i];r={PurePosixPath(x).parts[0] for x in n if x};c={"crc":z.testzip() is None,"single_root":r=={root},"path_safe":all(not PurePosixPath(x).is_absolute() and ".." not in PurePosixPath(x).parts and "\\" not in x for x in n),"duplicate_free":len(n)==len(set(n)),"symlink_free":all(not stat.S_ISLNK((x.external_attr>>16)&0xffff) for x in i)};m={PurePosixPath(*PurePosixPath(x.filename).parts[1:]).as_posix():z.read(x) for x in i if not x.is_dir()}
 return m,c
def run(a,cwd,timeout=40):
 p=subprocess.run(a,cwd=cwd,capture_output=True,text=True,encoding="utf-8",errors="replace",timeout=timeout,check=False);return {"argv":a,"exit_code":p.returncode,"stdout":p.stdout,"stderr":p.stderr}
def compile_sv(t,d,label,top="gap_v54_changed_surface",extra=None):
 p=d/(label+".sv");p.write_text(t,encoding="utf-8",newline="\n");a=[str(IV),"-g2012","-tnull","-s",top]+(extra or [])+[str(p)];r=run(a,d);r["source_sha256"]=h(t.encode());return r
def focused(ext:str):
 b=ext.replace("u_NDP_Top_new.clk_sg","clk_sg").replace("u_NDP_Top_new.rst_n_sg","rst_n_sg").replace("u_NDP_Top_new.clk_db","clk_db").replace("u_NDP_Top_new.rst_n_db","rst_n_db");s=b.index("    generate\n");e=b.index("    endgenerate\n",s)+len("    endgenerate\n");b=b[:s]+b[e:]
 b=re.sub(r"logic \[`SLICE_GROUP_SIZE-1:0\]\[`SLICE_GROUP_NUM-1:0\]\[4:0\] (return_obs_v54_[a-z0-9_, ]+);",lambda m:"logic "+m.group(1)+" [4][4][5];",b)
 b=b.replace("logic return_obs_v54_remote_mon [4][4][5];","logic [4:0] return_obs_v54_remote_mon [4][4];")
 b=b.replace("logic [`SLICE_GROUP_SIZE-1:0][`SLICE_GROUP_NUM-1:0][4:0][1:0] return_obs_v54_req_v_mon, return_obs_v54_req_r_mon, return_obs_v54_w_v_mon, return_obs_v54_w_r_mon;","logic return_obs_v54_req_v_mon [4][4][5][2], return_obs_v54_req_r_mon [4][4][5][2], return_obs_v54_w_v_mon [4][4][5][2], return_obs_v54_w_r_mon [4][4][5][2];")
 b=b.replace("logic [`SLICE_GROUP_SIZE-1:0][`SLICE_GROUP_NUM-1:0][1:0] return_obs_v54_g_req_v_mon, return_obs_v54_g_req_r_mon, return_obs_v54_g_req_wr_mon, return_obs_v54_g_w_v_mon, return_obs_v54_g_w_r_mon, return_obs_v54_g_w_wr_mon;","logic return_obs_v54_g_req_v_mon [4][4][2], return_obs_v54_g_req_r_mon [4][4][2], return_obs_v54_g_req_wr_mon [4][4][2], return_obs_v54_g_w_v_mon [4][4][2], return_obs_v54_g_w_r_mon [4][4][2], return_obs_v54_g_w_wr_mon [4][4][2];")
 return "`define GLB_SLICE_NUM 28\n`define SLICE_GROUP_SIZE 4\n`define SLICE_GROUP_NUM 4\nmodule gap_v54_changed_surface;logic clk_sg,clk_db,rst_n_sg,rst_n_db;bit return_obs_enabled;integer return_obs_fd;logic return_obs_pair_m4_finish_mon [4][4];\n"+b+"\nendmodule\n"
def probe(bad=None):
 leaves=["slice_remote_req_flag","mse2hub_req_valid[4][0]","hub2mse_req_ready[4][0]","mse2hub_wdata_valid[4][0]","hub2mse_wdata_ready[4][0]","slice_global_req_fifo_in_valid[0]","slice_global_req_fifo_in_ready[0]","slice_global_req_fifo_wr_en[0]","slice_global_wdata_fifo_in_valid[0]","slice_global_wdata_fifo_in_ready[0]","slice_global_wdata_fifo_wr_en[0]"]
 if bad:leaves[10]=bad
 return "module gap_v54_xmr_probe;slice2hub_crossbar dut();\n"+"\n".join(f"wire p{i}=|dut.{x};" for i,x in enumerate(leaves))+"\nendmodule\n"
def main():
 ap=argparse.ArgumentParser();ap.add_argument("--target-zip",type=Path,required=True);ap.add_argument("--runner-report",type=Path,required=True);ap.add_argument("--output",type=Path,required=True);a=ap.parse_args();target=a.target_zip.resolve();errors=[];m,arc=zmap(target,NAME);src,sarc=zmap(SOURCE,SOURCE_NAME)
 if sha(SOURCE)!=SOURCE_SHA:errors.append("source_sha")
 errors += ["archive:"+k for k,v in arc.items() if not v];man=json.loads(m["TEST_PACKAGE_MANIFEST.json"]);payload={k:v for k,v in m.items() if k!="TEST_PACKAGE_MANIFEST.json"};decl=man["files"]
 mc={"exact_set":set(payload)==set(decl),"per_file":all(decl[k]["size_bytes"]==len(v) and decl[k]["sha256"]==h(v) for k,v in payload.items()),"identity":man.get("install_name")==NAME,"source":man.get("source_package",{}).get("sha256")==SOURCE_SHA,"allowlist89":len(man.get("return_allowlist",[]))==89,"formal48":len(man.get("readback_checks",[]))==48,"current_rules":man["rule_receipts"].get("server_package_rule_sha256")==SERVER_SHA and man["rule_receipts"].get("generation_index_sha256")==INDEX_SHA};errors += ["manifest:"+k for k,v in mc.items() if not v]
 norm={k:v.replace(NAME.encode(),SOURCE_NAME.encode()) for k,v in m.items()};changed=sorted(k for k in set(src)|set(norm) if src.get(k)!=norm.get(k));expected=sorted(["PREPARE_AND_RUN.sh","README.md","SERVER_RUNTIME_LAYOUT_CONTRACT.json","TEST_PACKAGE_MANIFEST.json","package_tools/gap_node0071_complete_server_runtime.py","package_tools/gap_node0071_mse4_route_factor_decision.py","package_tools/gap_node0071_remote_owner_false_accept_decision.py","provenance/v53_to_v54_remote_owner_false_accept.json","tb_probe/native_return_observer.svh"])
 freeze={"changed_exact":changed==expected,"source_safe":all(sarc.values()),"workload_equal":all(src.get(k)==norm.get(k) for k in src if k.startswith("workload/")),"timeout_equal":[x for x in norm["PREPARE_AND_RUN.sh"].splitlines() if b"timeout " in x]==[x for x in src["PREPARE_AND_RUN.sh"].splitlines() if b"timeout " in x],"no_rtl":not any(k.startswith("rtl/") for k in m)};errors += ["freeze:"+k for k,v in freeze.items() if not v]
 obs=m["tb_probe/native_return_observer.svh"].decode();ext=obs[obs.index(MARKER):];sem={"owner_sg":"always @(posedge u_NDP_Top_new.clk_sg" in ext,"report_db":"always @(posedge u_NDP_Top_new.clk_db" in ext,"all_mse":"for(genvar v54_m=0;v54_m<5;v54_m++)" in ext,"both_ch":"for(genvar v54_ch=0;v54_ch<2;v54_ch++)" in ext,"owner_mismatch":"owner!=4" in ext,"no_fifo_write":"!return_obs_v54_g_w_wr_mon" in ext,"separate_budgets":"return_obs_v54_vcount<64" in ext and "return_obs_v54_fcount<128" in ext,"minimal_string":"event=%0s" in ext};errors += ["sem:"+k for k,v in sem.items() if not v]
 with tempfile.TemporaryDirectory(prefix="gap-v54-hdl-") as td:
  d=Path(td);f=focused(ext);pos=compile_sv(f,d,"positive");dele=compile_sv(f.replace("logic return_obs_pair_m4_finish_mon [4][4];","",1),d,"delete_decl");typo=compile_sv(f.replace("return_obs_pair_m4_finish_mon[g][s]","return_obs_pair_m4_finish_mom[g][s]",1),d,"typo");p=d/"probe.sv";p.write_text(probe(),encoding="utf-8");argv=[str(IV),"-g2012","-tnull","-s","gap_v54_xmr_probe","-I",str(INC),str(FIFO),str(CROSS),str(p)];xp=run(argv,d);bp=d/"bad.sv";bp.write_text(probe("slice_global_wdata_fifo_wr_ez[0]"),encoding="utf-8");bad=run(argv[:-1]+[str(bp)],d);sp=d/"sib.sv";sp.write_text(probe("wr_fifo_gen[0].slice_global_wdata_fifo_wr_en[0]"),encoding="utf-8");sib=run(argv[:-1]+[str(sp)],d);ct=CROSS.read_text(encoding="utf-8");ct=ct.replace("    wire [`MSE_REQ_CHL_NUM-1:0]                            slice_global_wdata_fifo_wr_en;\n","",1);cp=d/"cross_deleted.sv";cp.write_text(ct,encoding="utf-8");leaf=run([str(IV),"-g2012","-tnull","-s","gap_v54_xmr_probe","-I",str(INC),str(FIFO),str(cp),str(p)],d)
 hc={"positive":pos["exit_code"]==0,"delete_decl":dele["exit_code"]!=0,"typo":typo["exit_code"]!=0,"actual_xmr":xp["exit_code"]==0,"rename":bad["exit_code"]!=0,"sibling":sib["exit_code"]!=0,"delete_leaf":leaf["exit_code"]!=0};errors += ["hdl:"+k for k,v in hc.items() if not v]
 with tempfile.TemporaryDirectory(prefix="gap-v54-pred-") as td:
  d=Path(td);s=d/"p.py";o=d/"o.json";s.write_bytes(m["package_tools/gap_node0071_remote_owner_false_accept_decision.py"]);pr=run([sys.executable,str(s),"self-test","--output",str(o)],d);pp=json.loads(o.read_text()) if o.is_file() else {};pr["payload"]=pp;pr["pass"]=pr["exit_code"]==0 and pp.get("pass") is True and all(pp.get("checks",{}).values())
 if not pr["pass"]:errors.append("predicate")
 rr=json.loads(a.runner_report.read_text());rt=m["PREPARE_AND_RUN.sh"].decode();rc={"plusarg":"+RETURN_OBS_REMOTE_OWNER_FALSE_ACCEPT" in rt,"parser":"gap_node0071_remote_owner_false_accept_decision.py" in rt,"harness":rr.get("valid") is True and rr.get("errors")==[],"parser_exit":rr.get("checks",{}).get("normal_all_decision_parsers_exit_zero") is True,"stderr_empty":rr.get("checks",{}).get("normal_decision_parser_stderr_empty") is True};errors += ["runner:"+k for k,v in rc.items() if not v]
 out={"schema":"gap-node0071-v54-family-validation-v1","analysis_owner_thread":"019fa366-cb1f-7ae2-880c-f527be0680cd","return_target_thread":"019fbec2-fe93-7e03-9314-cff6f222f33d","target_zip":str(target.relative_to(ROOT)).replace("\\","/"),"target_zip_bytes":target.stat().st_size,"target_zip_sha256":sha(target),"archive_checks":arc,"manifest_checks":mc,"freeze_checks":freeze,"changed_members":changed,"observer_semantics":sem,"hdl_scope":{"tool":str(IV),"checks":hc,"positive":pos,"delete_declaration":dele,"typo":typo,"actual_xmr":xp,"rename":bad,"wrong_sibling":sib,"delete_leaf":leaf,"actual_crossbar_sha256":sha(CROSS),"claim_boundary":"Exact changed observer syntax and current crossbar private-leaf name resolution; no DUT simulation."},"predicate_trace":pr,"runner_checks":rc,"valid":not errors,"errors":errors,"claim_boundary":"Exact final ZIP/local changed surfaces only; no server/DUT run, natural terminal, formal D, E3, E4 or E5."};write(a.output,out);print(json.dumps({"output":str(a.output),"sha256":sha(a.output),"valid":not errors,"errors":errors}));return 0 if not errors else 1
if __name__=="__main__":raise SystemExit(main())
